# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: nodejs:14

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "db:mongodb-enterprise"

# The configuration of app when it is exposed to the web.
web:
  commands:
    start: "node ./server/index.js"

  locations:
    '/':
      allow: false
      passthru: true

# The size of the persistent disk of the application (in MB).
disk: 512

hooks:
  build: |
    set -e
    cd ./server && npm install
    cd ..
    npm install
    npm run build
    echo "\n\n"
    [ -f "build/index.html" ] && { echo "An index.html file was found in dist/ so the build was likely successful. Yay.\n\n"; exit 0;} || { echo "Build failure... no index.html found in dist/\n\n "; exit 1;}
